name: React.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # Add more Node.js versions as needed.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build if present
      run: npm run build --if-present

    - name: Trigger server update
      run: |
        cd /var/www/html/monorepo/actions-runner/_work/monorepo/monorepo/blog_react
        sh /var/www/html/monorepo/pull.sh
